export const ErrorCode = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // Resources
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FOLDER_NOT_FOUND: 'FOLDER_NOT_FOUND',

  // Share tokens
  SHARE_TOKEN_NOT_FOUND: 'SHARE_TOKEN_NOT_FOUND',
  SHARE_TOKEN_USED: 'SHARE_TOKEN_USED',
  SHARE_TOKEN_EXPIRED: 'SHARE_TOKEN_EXPIRED',

  // Generic
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  STREAM_ERROR: 'STREAM_ERROR',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  NO_FILE: 'NO_FILE',
} as const;

export type TErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
